- hosts: localhost
  tasks:
  
  - name: create s3 bucket
    s3_bucket: 
      name: "{{ bucket_name }}"
      region: "{{ s3_region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      
  - name: sync files to s3
    s3_sync:
      bucket: "{{ bucket_name }}"
      region: "{{ s3_region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      file_root: "{{ local_path_html }}"
      file_change_strategy: force
      permission: public-read
        

  - name: add website configuration to bucket
    s3_website:
      name: "{{ bucket_name }}"
      region: "{{ s3_region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      suffix: index.html
      error_key: errors.html
      state: present
  
  
  - name: Create a fly hostname
    fly:
      command: create_hostname
      fly_auth_key: "{{ fly_auth_key }}"
      site: "{{ site }}"
      hostname: "{{ hostname }}"
    register: result

  - pause:
      prompt: "Set your DNS CNAME record for {{ hostname }} to point to {{ result.response.preview_hostname }}"
    
  - name: Add a fly backend
    fly:
      command: add_backend
      fly_auth_key: "{{ fly_auth_key }}"
      site: "{{ site }}"
      backend_name: "my_s3_static_site"
      backend_type: "aws_s3"
      backend_settings: 
        bucket: "{{ bucket_name }}"
        region: "{{ s3_region }}"
    register: result

  
  - name: Add a fly rule
    fly:
      command: add_rule
      fly_auth_key: "{{ fly_auth_key }}"
      site: "{{ site }}"
      hostname: "{{ hostname }}"
      backend_id: '{{ result.id }}'
      action_type: "rewrite"
      path: "/"
      priority: "10"
      path_replacement: "/index.html"